parameters: {}
environment: {
  CLIENT_ID: "${CLIENT_ID}"
}
packages:
  - name: authentication
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: getUserAccessToken
        binary: false
        main: "lib/index.js"
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment: {
          CLIENT_SECRET: "${CLIENT_SECRET}"
        }
        annotations: {}
        limits: {
          memory: 128
        }
  - name: agreements
    shared: false
    environment: {
      REPOSITORY: "${REPOSITORY}",
      PRIVATE_KEY: "${PRIVATE_KEY}"
    }
    parameters: {}
    annotations: {}
    functions:
      - name: getAgreement
        binary: false
        main: ""
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {
          memory: 128
        }
      - name: updateAgreementInputValues
        binary: false
        main: ""
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {
          memory: 128
        }
